import { useState, useEffect } from "react";
import { useParams, useNavigate } from "react-router";
import {
  ArrowLeft,
  ArrowDown,
  FileCheck,
  Upload,
  Share2,
  BarChart3,
  FileWarning,
  CheckCircle2,
  AlertCircle,
} from "lucide-react";
import { toast } from "sonner";
import { useAuth } from "@/contexts/AuthContext";
import { useManuscripts } from "../hooks/useManuscripts";
import StatusBadge from "@/components/common/StatusBadge";
import ClassificationBadge from "@/components/common/ClassificationBadge";
import ReadinessChecklist from "../components/ReadinessChecklist";
import IssueAssignment from "../components/IssueAssignment";
import PublishAction from "../components/PublishAction";
import PostPublicationActions from "../components/PostPublicationActions";
import ImpactTracking from "../components/ImpactTracking";
import PostPublicationMgmt from "../components/PostPublicationMgmt";
import EditMetadataModal from "../components/EditMetadataModal";
import AssignDOIModal from "../components/AssignDOIModal";
import FileUploadModal from "../components/FileUploadModal";
import ArticlePreviewModal from "../components/ArticlePreviewModal";
import MetadataExportModal from "../components/MetadataExportModal";
import type { Manuscript } from "../types";

export default function ArticleDetail() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const { role } = useAuth();
  const isAuthor = role === "author";

  const {
    getById,
    getReadinessStatus,
    publishManuscript,
    saveMetadata,
    assignDOI,
    autoGenerateDOI,
    uploadFile,
    returnToRevision,
    retractManuscript,
    assignIssue,
    refreshMetrics,
  } = useManuscripts();

  const [manuscript, setManuscript] = useState<Manuscript | null>(null);
  const [loading, setLoading] = useState(true);

  // Modal states
  const [showMetadataModal, setShowMetadataModal] = useState(false);
  const [showDOIModal, setShowDOIModal] = useState(false);
  const [showFileUploadModal, setShowFileUploadModal] = useState(false);
  const [showArticlePreview, setShowArticlePreview] = useState(false);
  const [showMetadataExport, setShowMetadataExport] = useState(false);

  // Fetch manuscript on mount
  useEffect(() => {
    async function fetch() {
      if (!id) return;
      setLoading(true);
      const data = await getById(id);
      setManuscript(data);
      setLoading(false);
    }
    fetch();
  }, [id, getById]);

  // Refetch helper
  const refetch = async () => {
    if (!id) return;
    const data = await getById(id);
    setManuscript(data);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="text-center">
          <div className="size-8 border-3 border-[#3f4b7e]/20 border-t-[#3f4b7e] rounded-full animate-spin mx-auto mb-4" />
          <p className="text-sm text-[#6b7280] font-['Public_Sans',sans-serif]">
            Loading manuscript...
          </p>
        </div>
      </div>
    );
  }

  if (!manuscript) {
    return (
      <div className="flex items-center justify-center h-screen">
        <div className="text-center">
          <h2 className="font-['Newsreader',serif] text-[24px] text-[#1a1c1c] mb-2">
            Manuscript Not Found
          </h2>
          <p className="text-sm text-[#6b7280] font-['Public_Sans',sans-serif] mb-4">
            The manuscript ID "{id}" does not exist.
          </p>
          <button
            onClick={() => navigate(isAuthor ? "/author" : "/publication/dashboard")}
            className="px-4 py-2 bg-[#3f4b7e] text-white rounded text-sm font-['Public_Sans',sans-serif] hover:bg-[#3f4b7e]/90 transition-colors"
          >
            Back to Dashboard
          </button>
        </div>
      </div>
    );
  }

  const readiness = getReadinessStatus(manuscript);
  const isPublished = manuscript.status === "Published";

  return (
    <>
      {/* Header */}
      <header className="bg-white border-b border-[#e0e0e0] sticky top-0 z-50">
        <div className="px-8 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <button
                onClick={() => navigate(isAuthor ? "/author" : "/publication/dashboard")}
                className="p-2 hover:bg-[#f5f5f5] rounded transition-colors"
              >
                <ArrowLeft className="size-5 text-[#1a1c1c]" />
              </button>
              <div>
                <h1 className="font-['Newsreader',serif] text-[20px] text-[#3f4b7e]">
                  Publication Workflow
                </h1>
                <p className="text-xs text-[#6b7280] font-['Public_Sans',sans-serif]">
                  Manuscript ID: {manuscript.id.slice(0, 8)}...
                </p>
              </div>
            </div>
            <div className="flex items-center gap-3">
              <ClassificationBadge classification={manuscript.classification} />
              <StatusBadge status={manuscript.status} />
            </div>
          </div>
        </div>
      </header>

      {/* Main Workflow Container */}
      <main className="px-8 py-12">
        {/* Workflow Title */}
        <div className="mb-12">
          <div className="flex items-center gap-3 mb-4">
            <span className="text-[10px] tracking-[1px] uppercase text-[#3f4b7e] font-['Public_Sans',sans-serif]">
              MANUSCRIPT LIFECYCLE WORKFLOW
            </span>
            <div className="h-px bg-[#e0e0e0] flex-1 max-w-[200px]" />
            <ClassificationBadge classification={manuscript.classification} />
          </div>
          <h2 className="font-['Newsreader',serif] text-[48px] text-[#1a1c1c] leading-[60px]">
            {manuscript.title}
          </h2>
          <p className="font-['Newsreader',serif] italic text-[18px] text-[#6b7280] mt-2 leading-[29.25px]">
            {manuscript.authors.join(", ")}
          </p>
        </div>

        {/* Workflow Steps */}
        <div className="relative">
          {/* Vertical Progress Line */}
          <div className="absolute left-8 top-0 bottom-0 w-0.5 bg-gradient-to-b from-[#3f4b7e] via-[#F5C344] to-[#e0e0e0]" />

          {/* Stage 1: Production & Readiness */}
          <div className="relative mb-8">
            <div className="flex items-start gap-6">
              <div className="relative z-10 flex items-center justify-center size-16 bg-[#e8eaf6] rounded-full border-4 border-white shadow-md">
                <FileCheck className="size-7 text-[#3f4b7e]" />
              </div>
              <div className="flex-1">
                <div className="bg-white rounded-lg shadow-sm border border-[#e0e0e0] p-8">
                  <div className="flex items-center justify-between mb-6">
                    <div>
                      <h3 className="font-['Newsreader',serif] text-[24px] text-[#1a1c1c] leading-[32px]">
                        Production & Readiness
                      </h3>
                      <p className="text-sm text-[#6b7280] font-['Public_Sans',sans-serif] mt-1">
                        {readiness.isReady
                          ? "All requirements met - Ready to publish"
                          : "Complete all requirements to enable publication"}
                      </p>
                    </div>
                    {readiness.isReady ? (
                      <div className="flex items-center gap-2 px-4 py-2 bg-[#e8f5e9] rounded">
                        <CheckCircle2 className="size-4 text-[#2e7d32]" />
                        <span className="text-xs uppercase tracking-wider text-[#2e7d32] font-['Public_Sans',sans-serif]">
                          Ready
                        </span>
                      </div>
                    ) : (
                      <div className="flex items-center gap-2 px-4 py-2 bg-[#fff8e1] rounded">
                        <AlertCircle className="size-4 text-[#f57c00]" />
                        <span className="text-xs uppercase tracking-wider text-[#f57c00] font-['Public_Sans',sans-serif]">
                          Action Required
                        </span>
                      </div>
                    )}
                  </div>

                  {/* Readiness Checklist */}
                  <ReadinessChecklist
                    manuscript={manuscript}
                    readiness={readiness}
                    isAuthor={isAuthor}
                    onEditMetadata={() => setShowMetadataModal(true)}
                    onUploadFile={() => setShowFileUploadModal(true)}
                    onAssignDOI={() => setShowDOIModal(true)}
                    onReturnToRevision={async () => {
                      await returnToRevision(manuscript.id);
                      navigate("/publication/dashboard");
                    }}
                  />

                  {/* Manuscript Details */}
                  <div className="grid grid-cols-2 gap-6">
                    <div className="p-4 bg-[#f5f5f5] rounded-lg border border-[#e0e0e0]">
                      <h5 className="text-xs uppercase tracking-wider text-[#3f4b7e] font-['Public_Sans',sans-serif] mb-2">
                        Abstract
                      </h5>
                      <p className="text-sm text-[#6b7280] font-['Public_Sans',sans-serif] leading-relaxed">
                        {manuscript.abstract}
                      </p>
                    </div>
                    <div className="p-4 bg-[#f5f5f5] rounded-lg border border-[#e0e0e0]">
                      <h5 className="text-xs uppercase tracking-wider text-[#3f4b7e] font-['Public_Sans',sans-serif] mb-2">
                        Keywords
                      </h5>
                      <div className="flex flex-wrap gap-2">
                        {manuscript.keywords.map((keyword, index) => (
                          <span
                            key={index}
                            className="px-3 py-1 bg-white text-xs text-[#1a1c1c] font-['Public_Sans',sans-serif] rounded-full border border-[#e0e0e0]"
                          >
                            {keyword}
                          </span>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>

          {/* Connector */}
          {!isAuthor && (
            <div className="flex items-center justify-center my-6 relative">
              <div className="absolute left-8 flex items-center justify-center">
                <ArrowDown className="size-6 text-[#3f4b7e] animate-bounce" />
              </div>
            </div>
          )}

          {/* Issue Assignment (before publish) */}
          {!isPublished && !isAuthor && (
            <div className="relative mb-8">
              <div className="flex items-start gap-6">
                <div className="w-16" />
                <div className="flex-1">
                  <IssueAssignment
                    currentAssignment={manuscript.issue_assignment}
                    onAssign={(val) => assignIssue(manuscript.id, val).then(async (s) => { if (s) await refetch(); return s; })}
                  />
                </div>
              </div>
            </div>
          )}

          {/* Stage 2: Publish Action */}
          {!isAuthor && (
            <div className="relative mb-8">
              <div className="flex items-start gap-6">
                <div className="relative z-10 flex items-center justify-center size-16 bg-[#F5C344] rounded-full border-4 border-white shadow-lg">
                  <Upload className="size-7 text-[#3f4b7e]" />
                </div>
                <div className="flex-1">
                  <PublishAction
                    manuscript={manuscript}
                    isPublished={isPublished}
                    readiness={readiness}
                    onPublish={async () => {
                      const success = await publishManuscript(manuscript.id);
                      if (success) await refetch();
                      return success;
                    }}
                  />
                </div>
              </div>
            </div>
          )}

          {/* Stages 3-5: Post-publication (only if published) */}
          {isPublished && (
            <>
              {/* Connector */}
              <div className="flex items-center justify-center my-6 relative">
                <div className="absolute left-8 flex items-center justify-center">
                  <ArrowDown className="size-6 text-[#F5C344] animate-bounce" />
                </div>
              </div>

              {/* Stage 3: Post-Publication Actions */}
              <div className="relative mb-8">
                <div className="flex items-start gap-6">
                  <div className="relative z-10 flex items-center justify-center size-16 bg-[#fff8e1] rounded-full border-4 border-white shadow-md">
                    <Share2 className="size-7 text-[#F5C344]" />
                  </div>
                  <div className="flex-1">
                    <PostPublicationActions
                      manuscript={manuscript}
                      onShowArticlePreview={() => setShowArticlePreview(true)}
                      onExportMetadata={() => {
                        setShowMetadataExport(true);
                        toast.success("Metadata exported successfully");
                      }}
                    />
                  </div>
                </div>
              </div>

              {/* Connector */}
              <div className="flex items-center justify-center my-6 relative">
                <div className="absolute left-8 flex items-center justify-center">
                  <ArrowDown className="size-6 text-[#e0e0e0] animate-bounce" />
                </div>
              </div>

              {/* Stage 4: Impact Tracking */}
              {manuscript.metrics && (
                <div className="relative mb-8">
                  <div className="flex items-start gap-6">
                    <div className="relative z-10 flex items-center justify-center size-16 bg-[#fff8e1] rounded-full border-4 border-white shadow-md">
                      <BarChart3 className="size-7 text-[#F5C344]" />
                    </div>
                    <div className="flex-1">
                      <ImpactTracking
                        metrics={manuscript.metrics}
                        onRefresh={async () => {
                          await refreshMetrics(manuscript.id);
                          await refetch();
                        }}
                      />
                    </div>
                  </div>
                </div>
              )}

              {/* Stage 5: Post-Publication Management */}
              {!isAuthor && (
                <>
                  {/* Connector */}
                  <div className="flex items-center justify-center my-6 relative">
                    <div className="absolute left-8 flex items-center justify-center">
                      <ArrowDown className="size-6 text-[#e0e0e0]" />
                    </div>
                  </div>

                  <div className="relative">
                    <div className="flex items-start gap-6">
                      <div className="relative z-10 flex items-center justify-center size-16 bg-[#fff8e1] rounded-full border-4 border-white shadow-md">
                        <FileWarning className="size-7 text-[#f57c00]" />
                      </div>
                      <div className="flex-1">
                        <PostPublicationMgmt
                          manuscript={manuscript}
                          onRetractManuscript={async () => {
                            const success = await retractManuscript(manuscript.id);
                            if (success) await refetch();
                            return success;
                          }}
                          onReturnToRevision={async () => {
                            const success = await returnToRevision(manuscript.id);
                            if (success) await refetch();
                            return success;
                          }}
                        />
                      </div>
                    </div>
                  </div>
                </>
              )}
            </>
          )}
        </div>

        {/* Footer Info */}
        <div className="mt-12 p-6 bg-white rounded-lg border border-[#e0e0e0]">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="text-sm text-[#6b7280] font-['Public_Sans',sans-serif]">
                Submitted: {new Date(manuscript.created_at).toLocaleDateString("en-US", {
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                })}
              </div>
              {manuscript.published_at && (
                <>
                  <div className="h-4 w-px bg-[#e0e0e0]" />
                  <div className="text-sm text-[#6b7280] font-['Public_Sans',sans-serif]">
                    Published: {new Date(manuscript.published_at).toLocaleDateString("en-US", {
                      year: "numeric",
                      month: "long",
                      day: "numeric",
                    })}
                  </div>
                </>
              )}
            </div>
            <div className="flex items-center gap-2">
              <div className={`size-2 rounded-full ${isPublished ? "bg-[#2e7d32]" : "bg-[#f57c00]"}`} />
              <span className={`text-sm font-['Public_Sans',sans-serif] ${isPublished ? "text-[#2e7d32]" : "text-[#f57c00]"}`}>
                {manuscript.status}
              </span>
            </div>
          </div>
        </div>
      </main>

      {/* Modals */}
      <EditMetadataModal
        open={showMetadataModal}
        onClose={() => setShowMetadataModal(false)}
        initialTitle={manuscript.title}
        initialAuthors={manuscript.authors}
        initialAbstract={manuscript.abstract}
        initialKeywords={manuscript.keywords}
        onSave={async (data) => {
          await saveMetadata(manuscript.id, data);
          await refetch();
        }}
      />

      <AssignDOIModal
        open={showDOIModal}
        onClose={() => setShowDOIModal(false)}
        currentDOI={manuscript.doi}
        onAutoGenerate={async () => {
          const result = await autoGenerateDOI(manuscript.id);
          if (result.success) await refetch();
          return result;
        }}
        onManualAssign={async (doi) => {
          await assignDOI(manuscript.id, doi);
          toast.success("DOI assigned manually");
          await refetch();
        }}
      />

      <FileUploadModal
        open={showFileUploadModal}
        onClose={() => setShowFileUploadModal(false)}
        onUpload={async (file) => {
          const success = await uploadFile(manuscript.id, file);
          if (success) await refetch();
          return success;
        }}
      />

      {showArticlePreview && (
        <ArticlePreviewModal
          open={showArticlePreview}
          onClose={() => setShowArticlePreview(false)}
          manuscript={manuscript}
        />
      )}

      {showMetadataExport && (
        <MetadataExportModal
          open={showMetadataExport}
          onClose={() => setShowMetadataExport(false)}
          manuscript={manuscript}
        />
      )}
    </>
  );
}
